name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore --configuration Release
        dotnet pack --configuration Release --output .
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
        dotnet nuget add source --username gilmae --password ${{ secrets.API_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/gilmae/index.json"
        dotnet nuget push "SimpleDbContext.Core.*.nupkg"  --api-key ${{ secrets.API_TOKEN }} --source "github"
        dotnet nuget push "SimpleDbContext.MySql*.nupkg"  --api-key ${{ secrets.API_TOKEN }} --source "github"
        dotnet nuget push "SimpleDbContext.Npgsqk.*.nupkg"  --api-key ${{ secrets.API_TOKEN }} --source "github"
        dotnet nuget push "SimpleDbContext.AspNetCore.*.nupkg"  --api-key ${{ secrets.API_TOKEN }} --source "github"
        dotnet nuget push "SimpleDbRepository.*.nupkg"  --api-key ${{ secrets.API_TOKEN }} --source "github"
