name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Prep
      run: |
          echo "::set-env name=BUILD_VER::1.0.$GITHUB_RUN_NUMBER"
          echo "::set-env name=CONFIG::Release"
          echo "::set-env name=NUGET_URL::https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          echo "::set-env name=SLN::SimpleDbContext.sln"
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: ${{ env.NUGET_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore --configuration Release
        dotnet pack --configuration Release --output .
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
        dotnet nuget push **/*.nupkg \
          --source ${{ env.NUGET_URL }} \
          --skip-duplicate
